# This is a basic workflow that is manually triggered

name: Create Nuget Package

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version of the package'
        default: '1.0.0'
        required: true
        type: text
          

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: github.actor
      run: echo ${{ github.repository_owner }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Output Run Number
      run: echo "${{ github.event.inputs.version }}.${{ GITHUB.RUN_ID }}"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version="${{ github.event.inputs.version }}.${{ GITHUB.RUN_ID }}"
    - name: Nuget Pack
      run: dotnet pack --configuration Release --no-build --include-symbols --verbosity normal
    - name: Nuget Push
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${GITHUB_TOKEN} --store-password-in-clear-text
        dotnet nuget push "MinimalApiRegister/bin/Release/MinimalApiRegister.${{ github.event.inputs.version }}.${{ GITHUB.RUN_ID }}.nupkg" --api-key ${GITHUB_TOKEN} --source github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
